-d C:\Users\gusta\OneDrive\Documentos\Projetos_Quartus\telinha_I2C\impl\gwsynthesis\telinha_I2C.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst C:\Users\gusta\OneDrive\Documentos\Projetos_Quartus\telinha_I2C\src\telinha_I2C.cst
-cfg C:\Users\gusta\OneDrive\Documentos\Projetos_Quartus\telinha_I2C\impl\pnr\device.cfg
-bit
-tr
-ph
-sdf
-ibs
-posp
-warning_all
-timing
-cst_error
-place_option 1
-route_maxfan 23
